# Site/SEO settings
email: mailto:rachioko@yahoo.com
permalink: /:year/:month/:day/:title/
google_analytics: 

author: Amarachi Okoroafor
title: Datasite by Rachi
description: Data Analysis Blog by Amarachi Okoroafor
url: https://rachioko.github.io
baseurl: https://rachioko.github.io
twitter_username: 
default_img: /images/banner.jpg

# Profile settings
name: Amarachi Okoroafor
profile_img: /images/banner.jpg
profile: Amarachi Okoroafor was born and raised in Nigeria. Interested in Artificial Intelligence and Machine Learning, he is beginning his journey into Data Science. He is also quite good at Football (on the pitch or with a controller).   
social:
  github: https://github.com/rachioko
  linkedin: https://www.linkedin.com/in/rachiokoroafor

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
